import assert from "node:assert/strict";
import {loadBundledFontRegistry} from "../dist/fonts-node.js";
import {createFontRegistry,OPFFontError} from "../dist/fonts.js";
import {renderSvg,resolvePresentation,svgToPng} from "../dist/index.js";
const fonts=await loadBundledFontRegistry();
const style={fontFamily:"Roboto",fontWeight:400};
const measure=fonts.textMeasurement.measure;
assert.ok(measure("WWW",25,style)>measure("iii",25,style)*3);
assert.equal(measure("Hello",25,style),measure("Hello",50,style)/2);
assert.throws(()=>measure("hello",25,{...style,fontFamily:"Not installed"}),OPFFontError);
assert.throws(()=>measure("你好",25,style),OPFFontError);
assert.throws(()=>createFontRegistry([{data:new Uint8Array([0,1,2])}]),OPFFontError);
const fallback=await loadBundledFontRegistry({fallbackFamily:"Roboto"});
assert.equal(fallback.textMeasurement.resolveStyle({...style,fontFamily:"Aptos"}).fontFamily,"Roboto");
assert.equal(fallback.substitutions[0].requestedFamily,"Aptos");
fallback.clearSubstitutions();assert.deepEqual(fallback.substitutions,[]);
const deck={design:{fontScheme:"roboto"},slides:[{title:"Measured typography",text:"AVATAR iii WWW office affine. ".repeat(16)}]};
const options={textMeasurement:fonts.textMeasurement,embeddedFonts:fonts.embeddedFonts};
const svg=renderSvg(deck,options);
assert.match(svg,/@font-face/);assert.match(svg,/data:font\/ttf;base64,/);
assert.deepEqual(svg,renderSvg(deck,options));
const png=await svgToPng(svg,{fontFiles:fonts.fontFiles,useBundledFonts:false,loadSystemFonts:false});
assert.ok(png.length>1000);
const geometry=resolvePresentation(deck,options).slides[0].geometry;
for(const item of geometry.items)if(item.text)for(const line of item.text.lines)assert.ok(measure(line,item.text.fontSize,item.textStyle)<=item.box.width+0.01);
assert.throws(()=>renderSvg(deck,{embeddedFonts:[{family:'bad";}',weight:400,dataUrl:'https://example.com/font.ttf'}]}));
console.log("Fonts: actual advances, scaling, strict missing fonts/glyphs, explicit substitution, embedding and raster output passed.");
