import assert from 'node:assert/strict';
import {loadOfficeFontRegistry} from '../dist/fonts-node.js';
import {createFontRegistry, FONT_COMPATIBILITY} from '../dist/fonts.js';
const registry=await loadOfficeFontRegistry({substitutionPolicy:"visual"});
const pairs={Calibri:'Carlito',Cambria:'Caladea',Arial:'Arimo','Times New Roman':'Tinos','Courier New':'Cousine',Georgia:'Gelasio'};
for(const [fontFamily,substitute] of Object.entries(pairs)) for(const fontWeight of [400,700]) for(const italic of [false,true]) {
  const style={fontFamily,fontWeight,italic,path:'slides.0.text'};
  const resolved=registry.resolveFont(style);
  assert.equal(resolved.resolvedFamily,substitute);
  assert.equal(resolved.compatibility,fontFamily==='Georgia'?'visual':'metric');
  assert.equal(resolved.path,style.path);
  assert.ok(registry.textMeasurement.measure('AVATAR office 1234',25,style)>0);
}
assert.equal(registry.embeddedFonts.length,33);
for(const face of registry.embeddedFonts) assert.ok(face.license?.length>1000);
const entries=registry.embeddedFonts.map(face=>({...face,data:new Uint8Array(Buffer.from(face.dataUrl.split(',')[1],'base64'))}));
const alias=createFontRegistry(entries,{aliases:{Carlito:'Arimo'},substitutionPolicy:'visual'});
assert.equal(alias.resolveFont({fontFamily:'Carlito',fontWeight:400}).compatibility,'exact');
assert.equal(alias.resolveFont({fontFamily:'Carlito',fontWeight:400}).resolvedFamily,'Carlito');
assert.equal(alias.resolveFont({fontFamily:'Calibri Light',fontWeight:300}).compatibility,'visual');
assert.equal(alias.resolveFont({fontFamily:'Aptos',fontWeight:400}).compatibility,'visual');
assert.equal(alias.resolveFont({fontFamily:'Calibri',fontWeight:500}).compatibility,'visual');
const metricOnly=createFontRegistry(entries,{substitutionPolicy:'metric'});
assert.throws(()=>metricOnly.resolveFont({fontFamily:'Georgia',fontWeight:400}),{code:'font-unavailable'});
for(const family of ['Calibri Light','Aptos','Calibri']) assert.throws(()=>metricOnly.resolveFont({fontFamily:family,fontWeight:500}),{code:'font-unavailable'});
const theme=createFontRegistry(entries,{substitutionPolicy:'metric',themeFonts:{minorLatin:'Calibri',majorLatin:'Cambria'},fallbackFamily:'Roboto'});
assert.equal(theme.resolveFont({fontFamily:'+mn-lt',fontWeight:400}).resolvedFamily,'Carlito');
assert.equal(theme.resolveFont({fontFamily:'+mj-lt',fontWeight:700}).resolvedFamily,'Caladea');
assert.throws(()=>theme.resolveFont({fontFamily:'+mn-ea',fontWeight:400}),{code:'unresolved-theme-font'});
assert.equal(theme.resolveFont({fontFamily:'Unknown Font',fontWeight:400}).compatibility,'generic');
for(const fontFamily of ['Wingdings','Wingdings 2','Wingdings 3','Webdings','Symbol']) assert.throws(()=>theme.resolveFont({fontFamily,fontWeight:400}),{code:'font-encoding-required'});
assert.throws(()=>theme.resolveFont({fontFamily:'Cambria Math',fontWeight:400}),{code:'math-font-required'});
assert.throws(()=>theme.textMeasurement.measure('你好',25,{fontFamily:'Calibri',fontWeight:400}),{code:'missing-glyph'});
const noBold=createFontRegistry(entries.filter(face=>face.weight===400),{substitutionPolicy:'metric'});
assert.throws(()=>noBold.resolveFont({fontFamily:'Calibri',fontWeight:700}),{code:'font-unavailable'});
const missingStyle=createFontRegistry(entries.filter(face=>!face.italic));
assert.throws(()=>missingStyle.resolveFont({fontFamily:'Carlito',fontWeight:400,italic:true}),{code:'font-style-unavailable'});
assert.throws(()=>createFontRegistry(entries,{substitutionPolicy:'best'}),{code:'invalid-font-policy'});
assert.ok(Object.isFrozen(FONT_COMPATIBILITY[0].substitutes));
registry.clearSubstitutions(); assert.deepEqual(registry.substitutions,[]);
console.log('Office font policy passed: 24 bundled faces, exact-first lookup, scoped metric claims, theme aliases, explicit approximate fallback, and symbol/math/coverage errors.');
